using System;

namespace Entities.DTO
{
    /// <summary>
    /// Données d'un calendrier.
    /// </summary>
    public class CalendarSimpleDto
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="CalendarSimpleDto"/> class.
        /// </summary>
        /// <autogeneratedoc />
        public CalendarSimpleDto()
        {
            this.Name = null!;
        }

        /// <summary>
        /// Obtient ou définit l'identifiant du calendier.
        /// </summary>
        public Guid Id { get; set; }

        /// <summary>
        /// Obtient ou définit l'URL de l'image
        /// </summary>
        public string? ImageUrl { get; set; }

        /// <summary>
        /// Obtient ou définit le nom.
        /// </summary>
        public string Name { get; set; }

        /// <summary>
        /// Obtient ou définit l'identifiant du donneur d'ordre.
        /// </summary>
        public Guid OriginatorId { get; set; }
    }
}