using System;
using System.Collections.Generic;

namespace Entities.DTO
{
    public class PossibleEntryCategoryDto
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="PossibleEntryCategoryDto"/> class.
        /// </summary>
        /// <autogeneratedoc />
        public PossibleEntryCategoryDto()
        {
            this.EntryFields = new List<EntryFieldDto>();
        }

        public int AddressBlockLevel { get; set; }
        public Guid CalendarId { get; set; }
        public string? CalendarName { get; set; }
        public int DescriptionLevel { get; set; }
        public int EmailLevel { get; set; }
        public Guid EntryCategoryId { get; set; }
        public string? EntryCategoryName { get; set; }
        public IEnumerable<EntryFieldDto> EntryFields { get; set; }
        public bool IsActive { get; set; }
        public int PhoneLevel { get; set; }
    }
}